{
 "title": "URL Shortener App Monitoring",
 "tags": [
  "app",
  "docker",
  "prometheus"
 ],
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"urlshortener\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"urlshortener\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "API Response Count",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{ method }} {{ handler }}" }
   ]
  }
 ]
}