{
 "title": "URL Shortener App Monitoring",
 "tags": [
  "app",
  "docker",
  "prometheus"
 ],
 "panels": [
  {
   "title": "EC2 CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "EC2 RAM Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Network I/O (Receive / Transmit)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "Receive - {{instance}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "Transmit - {{instance}}"
    }
   ]
  },
  {
   "title": "API Request Latency (avg by endpoint)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "API 500 Error Rate (Last 1m)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 22, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_response_status_total{code=\"500\"}[1m])",
     "legendFormat": "500 errors"
    }
   ]
  },
  {
   "title": "Frontend HTTP Status (Blackbox)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 22, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://url-shortener-frontend:80\"}"
    }
   ]
  }
 ]
}